name: Deploy Master

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4

    steps:
    - uses: actions/checkout@v3
    - name: deploy in server
      run: |
        sshpass -p ${{secrets.SSH_PASS}} ssh  jogjatec@valerion.sg.rapidplex.com -p
        source /home/jogjatec/virtualenv/aviationdigimon.com/3.8/bin/activate && cd /home/jogjatec/aviationdigimon.com/pertamina_survey
        git pull origin master

