name: Deploy Master

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: deploy in server
      run: |
        sshpass -p ${{secrets.SSH_PASS}}
        source /home/jogjatec/virtualenv/aviationdigimon.com/3.8/bin/activate && cd /home/jogjatec/aviationdigimon.com/pertamina_survey
        git pull origin master

